stages:
  - build
  - test
  - analyze

build:
  stage: build
  # Using Ubuntu image to ensure that installation commands are the same as for Ubuntu desktops
  image: ubuntu:latest
  cache:
    paths:
      - .pip
  before_script:
    - apt-get update
    - apt-get install -y autoconf lm-sensors gir1.2-gtk-3.0 python3-gi python3-pip
    # The language setting is required for installing PySensors
    - LANG=C.UTF-8 pip3 --cache-dir=.pip install -r requirements.txt
  script:
    - autoreconf -i
    - ./configure
    - make
    - make install

lint:
  stage: test
  when: manual
  allow_failure: true
  image: python:latest
  cache:
    paths:
    - .pip
  before_script:
  - python -V
  - pip --cache-dir=.pip install -r requirements.txt
  script:
  - pylint -j 0 *.py

cloc:
  stage: analyze
  when: manual
  image: alpine:latest
  before_script:
  - apk --no-cache add cloc
  script:
  - cloc . --exclude-list-file=clocignore.txt --report-file=cloc.txt --by-file-by-lang
  artifacts:
    paths:
    - cloc.txt
