
stages:
  - build

build:
  stage: build
  image: ubuntu:latest
  cache:
    paths:
      - .pip
  before_script:
    - apt-get update
    - apt-get install -y python3-pip python3-gi gir1.2-gtk-3.0
    - pip3 --cache-dir=.pip install -r requirements.txt
  script:
    - autoreconf -i
    - ./configure
    - make
    - make install
